FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

RUN addgroup -g 1001 -S nova
RUN adduser -S nova -u 1001

COPY --from=builder --chown=nova:nova /app/.next/standalone ./
COPY --from=builder --chown=nova:nova /app/.next/static ./.next/static
COPY --from=builder --chown=nova:nova /app/public ./public

USER nova
EXPOSE 3000

ENV PORT=3000
CMD ["node", "server.js"]
